---
- name: lab27 configure webserver
  hosts: servers
  become: yes
  tasks:
    - name: install Nginx
      dnf:
        name: nginx
        state: present

    - name: custome web page
      copy:
        content: "Hello from Ansible lab27 on RedHat!"
        dest: /usr/share/nginx/html/index.html

    - name: start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
