apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins-app
        image: nouraabdelnabi/jenkins-app:latest 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
spec:
  selector:
    app: jenkins-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort



