plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
  tag:service: db
  instance-state-name: ['running']
hostnames:
  - ip-address
compose:
  ansible_host: public-ip-address
key_groups:
  - prefix: tag
    key: tags
