- name: Add Jenkins Repo
  shell: "curl -fsSL https://pkg.jenkins.io/redhat-stable/jenkins.repo -o /etc/yum.repos.d/jenkins.repo"

- name: Import Jenkins GPG Key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    validate_certs: no

- name: Install Java and Jenkins
  dnf:
    name: 
      - java-17-openjdk
      - jenkins
    state: present
    disable_gpg_check: yes
